### ISSUE TITLE
Addon does not work in FastBoot mode

### ISSUE THREAD

**Issue by pkvince** [LucasHill/ember-print-this#23]
When runing in FastBoot mode, jQuery is not available and it makes the app crash when `ember-print-this` is installed.

By manually disabling FastBoot this fixes the problem, of by disabling the inclusion of the vendor script as documented here: [https://github.com/ember-fastboot/ember-cli-fastboot#appimport-in-an-addons-included-hook](https://github.com/ember-fastboot/ember-cli-fastboot#appimport-in-an-addons-included-hook)

I submitted a PR (#24)

Thank you!

**Comment by LucasHill** [comment]
@pkvince thanks for this! Just released with beta version 7.
