### ISSUE TITLE
[Feature request] Add a way to use the addon w/ fewer or no DOM modifications

### ISSUE THREAD

**Issue by bgentry** [LucasHill/ember-print-this#28]
I noticed that the `{{print-this}}` component adds two additional elements to the DOM: the `div` for the component itself, *plus* [another](https://github.com/LucasHill/ember-print-this/blob/6f2186f80f6a93e9c380de0b480650cf1bcc749e/addon/templates/components/print-this.hbs) inside of it that gets `defaultPrintClass`.

I have two requests:

1. At the very least it should be easy to get rid of one of these so there is only one additional element added to the DOM.
2. Is it possible to trigger a print without adding anything to the DOM? Maybe it would be possible to have a service that could be triggered via an action with any selector?

Maybe related to #17.

**Comment by LucasHill** [comment]
Both good ideas! I'll take a stab at those changes.

**Comment by LucasHill** [comment]
Kind of forgot about this for a bit sorry, but I just got those changes merged and released. Thanks for the idea!
