### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by spee** [LucasHill/ember-print-this#29]
(Auto)print does not seem to work on IE11 due to calling an undefined `assign` method:
Object doesn't support property or method: 'assign'.

**Comment by LucasHill** [comment]
Thanks for reporting this. I can fix it tonight. The issue is an object.assign usage. Ember has a polyfill (ember.merge). If you need a fix sooner you can include the Babel polyfill from the ember-cli-babel.

**Comment by spee** [comment]
Thanks for the quick reply. For other reasons I had to switch to a simple `window.print` instead of using the component anyway.

**Comment by LucasHill** [comment]
Released the fix to beta 9.
