### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by bracke** [LucasHill/ember-print-this#74]
Hi

On Ember 5 printthis 2.0 won't work due to using "import { assign } from '@ember/polyfills';" in the printthis service.

https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md
https://blog.emberjs.com/ember-5-0-released/

This seems to be fixed in the master branch.

Any chance of a new release with the change?

Kind regards
Bent Bracke

**Comment by LucasHill** [comment]
> Hi
> 
> On Ember 5 printthis 2.0 won't work due to using "import { assign } from '@ember/polyfills';" in the printthis service.
> 
> https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md https://blog.emberjs.com/ember-5-0-released/
> 
> This seems to be fixed in the master branch.
> 
> Any chance of a new release with the change?
> 
> Kind regards Bent Bracke

Absolutely, I’ll work on getting a new release out. This fell off my radar for awhile.

**Comment by bracke** [comment]
Would it perhaps be easier to do a release without all the other changes in master?
So the previous version +fix?

Kind regards
Bent Bracke

**Comment by LucasHill** [comment]
I tested removing the assign and that just kicks it to the next compatibility issue with Ember 5. I will work on getting a full fix out whether it be a simple patch to the last released version or finishing my modernization of the addon. Sorry for the delay.

**Comment by LucasHill** [comment]
@bracke I just release version 2.1.0, could you confirm if this unblocks you on ember 5? I tested in a fresh ember 5 app and it appears to be working.

**Comment by bracke** [comment]
It works, thank You!
